In [1]:
cd "../资料/Emre Neftci"

D:\资料\Emre Neftci


# Parameters:

# Results on test dataset:

In [2]:
import numpy as np

test_results = np.load('test_acc.npy')
print(test_results)

[[0.32762897 0.82775298 0.92733135]
 [0.35639881 0.88256448 0.80109127]
 [0.38008433 0.88033234 0.52095734]
 [0.37227183 0.8844246  0.18030754]
 [0.39521329 0.88938492 0.11011905]
 [0.37475198 0.88628472 0.10019841]
 [0.38318452 0.88740079 0.1031746 ]
 [0.4280754  0.8921131  0.09920635]
 [0.38529266 0.88839286 0.10019841]
 [0.40066964 0.89012897 0.09920635]
 [0.42571925 0.89025298 0.09920635]
 [0.42150298 0.89422123 0.10019841]
 [0.40749008 0.8922371  0.09920635]
 [0.42311508 0.89422123 0.09920635]
 [0.38169643 0.89335317 0.09920635]
 [0.39583333 0.90017361 0.09920635]
 [0.44469246 0.89508929 0.09920635]
 [0.42782738 0.89732143 0.10230655]
 [0.44506448 0.90327381 0.09920635]
 [0.42857143 0.89831349 0.09920635]
 [0.44804067 0.89620536 0.09920635]
 [0.41989087 0.9031498  0.09920635]
 [0.46366567 0.89707341 0.09920635]
 [0.42447917 0.89645337 0.09920635]
 [0.4343998  0.90711806 0.09920635]
 [0.44717262 0.89831349 0.10032242]
 [0.45337302 0.90513393 0.09920635]
 [0.45300099 0.89657738 0.09